In [2]:
from src.time_series_prep import *
import pandas as pd
from models.shared_layer import *
from torchviz import make_dot
from torchsummary import summary
from src.data_preprocessing import *
from src.visualizations import *
from src.global_configs import *
from src.time_series_prep import *
import logging

# Initialize logger
logging.basicConfig(
    filename='training.log',  # File where logs will be saved
    level=logging.INFO,  # Set logging level to INFO
    format='%(asctime)s - %(levelname)s - %(message)s',  # Log format
    # filemode='w'  # Overwrite log file on each run
)
logger = logging.getLogger()


In [5]:
scaler = process_all_csv_files(input_folder, output_folder_train, timestamp_col='ts', freq='5min', agg_func='mean')
model_type = 'shared-layer'
patients_list = ['559', '563', '570', '575', '588', '591', '540', '544', '552', '567', '584', '596']
prediction_horizon = 6

In [6]:
train_loader, validation_loader, all_train_loader, test_loader, input_shape, input_shape_test, output_shape, output_shape_test =  prepare_data_loader(
                                                                                    window_size,BATCH_SIZE, prediction_horizon,
                                                                                    model_type, split_ratio = 0.7, df = None, df_test = None, output_folder_train=output_folder_train, shuffle = False)
    

Shape of X (features): (12, 13618, 6)
Shape of y (targets): (12, 13618)
Shape of X_test (features): (12, 3939, 6)
Shape of y_test (targets): (12, 3939)


In [41]:
# i=0
# for x, y in all_train_loader:
#     print(np.array(x).shape)
    # patient_x = x[0:i+1]
    # patient_y  = [sublist[0:i+1] for sublist in y]
    # i+=1
    # print(np.array(patient_x).shape)
    # print(np.array(patient_y).shape)
    # break


(12, 64, 6, 1)
(12, 64, 6, 1)
(12, 64, 6, 1)
(12, 64, 6, 1)
(12, 64, 6, 1)
(12, 64, 6, 1)
(12, 64, 6, 1)
(12, 64, 6, 1)
(12, 64, 6, 1)
(12, 64, 6, 1)
(12, 64, 6, 1)
(12, 64, 6, 1)
(12, 64, 6, 1)
(12, 64, 6, 1)
(12, 64, 6, 1)
(12, 64, 6, 1)
(12, 64, 6, 1)
(12, 64, 6, 1)
(12, 64, 6, 1)
(12, 64, 6, 1)
(12, 64, 6, 1)
(12, 64, 6, 1)
(12, 64, 6, 1)
(12, 64, 6, 1)
(12, 64, 6, 1)
(12, 64, 6, 1)
(12, 64, 6, 1)
(12, 64, 6, 1)
(12, 64, 6, 1)
(12, 64, 6, 1)
(12, 64, 6, 1)
(12, 64, 6, 1)
(12, 64, 6, 1)
(12, 64, 6, 1)
(12, 64, 6, 1)
(12, 64, 6, 1)
(12, 64, 6, 1)
(12, 64, 6, 1)
(12, 64, 6, 1)
(12, 64, 6, 1)
(12, 64, 6, 1)
(12, 64, 6, 1)
(12, 64, 6, 1)
(12, 64, 6, 1)
(12, 64, 6, 1)
(12, 64, 6, 1)
(12, 64, 6, 1)
(12, 64, 6, 1)
(12, 64, 6, 1)
(12, 64, 6, 1)
(12, 64, 6, 1)
(12, 64, 6, 1)
(12, 64, 6, 1)
(12, 64, 6, 1)
(12, 64, 6, 1)
(12, 64, 6, 1)
(12, 64, 6, 1)
(12, 64, 6, 1)
(12, 64, 6, 1)
(12, 64, 6, 1)
(12, 64, 6, 1)
(12, 64, 6, 1)
(12, 64, 6, 1)
(12, 64, 6, 1)
(12, 64, 6, 1)
(12, 64, 6, 1)
(12, 64, 6

In [39]:
patient_y

[tensor([-1.2426, -1.3902]),
 tensor([-1.3417, -1.4305]),
 tensor([-1.4126, -1.4104]),
 tensor([-1.4126, -1.3701]),
 tensor([-1.3843, -1.3299]),
 tensor([-1.4126, -1.2695]),
 tensor([-1.4268, -1.2091]),
 tensor([-1.3984, -1.2091]),
 tensor([-1.3984, -1.2091]),
 tensor([-1.4551, -1.2494]),
 tensor([-1.4693, -1.2896]),
 tensor([-1.4409, -1.3097]),
 tensor([-1.4693, -1.2494]),
 tensor([-1.4409, -1.2695]),
 tensor([-1.3984, -1.2695]),
 tensor([-1.3984, -1.2091]),
 tensor([-1.3984, -1.1689]),
 tensor([-1.3559, -1.1085]),
 tensor([-1.3276, -1.0884]),
 tensor([-1.3559, -1.0682]),
 tensor([-1.3276, -1.0884]),
 tensor([-1.2142, -1.0682]),
 tensor([-1.0725, -1.0280]),
 tensor([-1.0867, -0.9676]),
 tensor([-1.2992, -0.7462]),
 tensor([-1.3701, -0.5047]),
 tensor([-1.3701, -0.5248]),
 tensor([-1.3984, -0.4443]),
 tensor([-1.3984, -0.3437]),
 tensor([-1.4268, -0.3638]),
 tensor([-1.4551, -0.2833]),
 tensor([-1.4693, -0.1626]),
 tensor([-1.4268, -0.1022]),
 tensor([-1.4126, -0.0016]),
 tensor([-1.38

In [36]:
patient_x[0]

tensor([[[-0.9308],
         [-0.9733],
         [-0.8883],
         [-0.7750],
         [-0.6616],
         [-0.5624]],

        [[-0.9733],
         [-0.8883],
         [-0.7750],
         [-0.6616],
         [-0.5624],
         [-0.4491]],

        [[-0.8883],
         [-0.7750],
         [-0.6616],
         [-0.5624],
         [-0.4491],
         [-0.3499]],

        [[-0.7750],
         [-0.6616],
         [-0.5624],
         [-0.4491],
         [-0.3499],
         [-0.3782]],

        [[-0.6616],
         [-0.5624],
         [-0.4491],
         [-0.3499],
         [-0.3782],
         [-0.3074]],

        [[-0.5624],
         [-0.4491],
         [-0.3499],
         [-0.3782],
         [-0.3074],
         [-0.2649]],

        [[-0.4491],
         [-0.3499],
         [-0.3782],
         [-0.3074],
         [-0.2649],
         [-0.2224]],

        [[-0.3499],
         [-0.3782],
         [-0.3074],
         [-0.2649],
         [-0.2224],
         [-0.2365]],

        [[-0.3782],
    